branch-defaults:
  master:
    environment: FLyinstyleWP
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: Flyinstyle
  default_platform: 64bit Amazon Linux 2015.03 v1.4.2 running PHP 5.6
  default_region: us-east-1
  profile: eb-cli
  sc: git
